GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/681fc0d1ab385696ce85e3ff

###

POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "Name Surname",
  "number": "111-222-333"
}

###

DELETE http://localhost:3001/api/persons/48715759